library(gdxrrw)
library(dplyr)
library(tidyr)
library(ggplot2)
igdx("C:/GAMS/49")

source("codes/S3_read_gms.R")

crop_file <- list.files(paste0(INPUT_DIR,"/GLOBIOM/"),pattern = "*.gdx", full.names = TRUE)
crop.dat <- gdxrrw::rgdx.param(file.path(crop_file), symName = "CROP_DATA")

# recode all factor columns to characters in crop.dat
crop.dat.proc <- crop.dat %>%
  mutate(across(where(is.factor), as.character)) %>%
  filter(SPECIES==ALLITEM | ALLITEM=="BaseArea", nchar(ALLTECH)==2) %>%
  mutate(ALLITEM=ifelse(ALLITEM=="BaseArea","BaseArea","Yield")) %>%
  pivot_wider(names_from=ALLITEM, values_from=CROP_DATA, values_fill = 0) %>%
  mutate(BaseArea=BaseArea*1000)

full.map <- readRDS(paste0(INPUT_DIR,"/mappings/SimU_CR_LU_map.rds"))
full.map <- full.map %>%
  rename("AllColRow"="ALLCOLROW", "ANYREGION"="ALLCOUNTRY", "AEZCLASS"="AezClass") %>%
  dplyr::select(-ColRow30)

# CRITICAL FIX: Join the spatial map BEFORE doing the duplication check
crop.dat.proc <- crop.dat.proc %>%
  left_join(full.map) # Make sure "SimUID" (or whatever the common key is) is explicitly stated or inherently matched

# ── 1. Correct for Spatial Mapping Duplication ──────────────────────────────
# Count duplicates generated by the spatial join
check <- crop.dat.proc %>%
  group_by(ANYREGION, AllColRow, AltiClass, SlpClass, SoilClass, AEZCLASS, SPECIES, ALLTECH) %>%
  summarise(duplication.fact = n(), .groups = "drop")

# Divide the area uniformly across the duplicated SimUIDs
crop.dat.proc <- crop.dat.proc %>%
  left_join(check, by = c("ANYREGION", "AllColRow", "AltiClass", "SlpClass", "SoilClass", "AEZCLASS", "SPECIES", "ALLTECH")) %>%
  mutate(BaseArea = BaseArea / duplication.fact)

# ── 2. Aggregate per SimUID with Weighted Yields ────────────────────────────
final.cropdat <- crop.dat.proc %>%
  group_by(SimUID, ALLTECH, SPECIES) %>%
  summarise(
    # Use weighted mean if area exists, fallback to normal mean if area is 0
    YLD = ifelse(
      sum(BaseArea, na.rm = TRUE) > 0,
      weighted.mean(Yield, w = BaseArea, na.rm = TRUE),
      mean(Yield, na.rm = TRUE)
    ),
    BaseArea = sum(BaseArea, na.rm = TRUE),
    .groups = "drop"
  )

# ── 3. Duplicate ALLTECH into Specific Scenarios (M1-M5) ────────────────────
tech_mapping <- tibble(
  ALLTECH = c("HI", "HI", "LI", "LI", "LI", "IR"),
  Scen    = c("M5.rf", "M4.rf", "M3.rf", "M2.rf", "M1.rf", "M5.ir")
)

final.cropdat <- final.cropdat %>%
  inner_join(tech_mapping, by = "ALLTECH", relationship = "many-to-many") %>%
  select(-ALLTECH) %>%
  rename(GLOBIOM_abr = SPECIES)

# Save the final file
saveRDS(final.cropdat, file = paste0(INPUT_DIR,"/EPIC/cropyieldsOLD_GLOBIOM.rds"))
